name: Update Publications from Scholar

on:
  schedule:
    - cron: '0 3 * * 0'  # Every Sunday 03:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch publications
        run: python update_pubs.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add publications.json
          git diff --quiet && echo "No changes" || (git commit -m "Update publications" && git push)
