name: Update Publications from Google Scholar

on:
  workflow_dispatch:     # allows manual trigger from GitHub Actions tab
  schedule:
    - cron: '0 3 * * 0'  # optional: run every Sunday at 03:00 UTC

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install scholarly

      - name: Run update_pubs.py
        run: python update_pubs.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add publications.json
          git diff --cached --quiet && echo "No changes to commit" || (
            git commit -m "Auto-update publications.json"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
          )
